### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zooool** [Jertzukka/xenforo-scraper#1]
Trying to run this results in:

```
 File "xenforo-scraper.py", line 40
    print(f"File sizes: Max: {bytesToShort(maxsize)}, Min: {bytesToShort(minsize)}")
```

**Comment by Jertzukka** [comment]
> Trying to run this results in:
> 
> ```
>  File "xenforo-scraper.py", line 40
>     print(f"File sizes: Max: {bytesToShort(maxsize)}, Min: {bytesToShort(minsize)}")
> ```

Means you're missing `convert.py` which is imported and use in `xenforo-scraper.py`. Make sure you have both python files in the same folder when ran.
